Context
PavelProl/junior-course-boilerplate pull request #10
Opened 2021-10-24 17:12 UTC by PavelProl

6_Context

2021-11-16 08:19 UTC, vislogurov requested changes

2021-11-16 08:19 UTC, vislogurov commented on src/App.js
> +function getMinValue(arr) {
Вынести все функции такого рода в папку utils, если что-то вне тела класса создаётся — значит можно вынести отдельно. В ином случае, если какая то из функций понадобится в другом компоненте, то придётся туда весь App целиком тащить.

2021-11-16 08:19 UTC, vislogurov commented on src/App.js
> +        console.log('filteredProducts', filteredProducts);
Логи нужно убрать, есть риск "запалить" пользовательские данные, если не исключить из сборки логи.

2021-11-16 08:19 UTC, vislogurov commented on src/components/ProductPage/ProductPage.js
> +    // handleCategoriesClick(event) {
Либо добавляй коммент почему закомменчено, либо убирай совсем

2021-11-16 08:19 UTC, vislogurov commented on src/App.js
>  import ProductPage from './components/ProductPage/ProductPage.js';
Замечания общего характера:

- url параметры должны передаваться в таком формате `?…``?param1=2345&param2=text`, `http://localhost:3000/clothes` вот в такой реализации `clothes` задан не как параметр, а как отдельная страница — тут будут проблемы с роутингом, если такая страница действительно появится.
`http://localhost:3000/?categories=clothes` должно быть например так.
- Если в браузере сразу открыть такой урл `http://localhost:3000/?categories=clothes` то должны открыться страница с уже активным фильтром по clothes. Сейчас это не реализовано. Работа с урлом должна быть и в cDm, не хватает чего-то такого
```
  componentDidMount() {
    const [, categoriesFromUrl] = window.location.search.split("=");
    const selectedCategory = categoriesFromUrl
      ? categoriesFromUrl.split(",")
      : [];
    this.setState({
      ...this.state,
      selectedCategory
    });

    window.addEventListener("popstate", this.setFromHistory);
  }
  ```
- Кнопка сбросить фильтры не сбрасывает категории в урле.
- http://s.csssr.ru/U0FMPH83W/20211116110949_.png если выбрать две категории, то в урле будет только одна из них

2021-12-26 12:25 UTC, PavelProl commented on src/App.js
>  import ProductPage from './components/ProductPage/ProductPage.js';
Максим, можешь пояснить пжлст? Не понял назначение отрывка categoriesFromUrl.split(",") во фрагменте кода cDM.
Я понял так, что если, допустим, у нас в url так:  ?param1=2345&param2=text, 
то строкой  const [, categoriesFromUrl] = window.location.search.split("=")
мы получаем в переменной categoriesFromUrl значение "text".
А вот что дальше происходит с помощью split(","), я не понял.

2021-12-27 07:18 UTC, vislogurov commented on src/App.js
>  import ProductPage from './components/ProductPage/ProductPage.js';
Смотри, `'?param1=books,clothes'.split("=")` вернёт тебе `["?param1", "books,clothes"]`. Первая половина массива нам не нужна, а вторую сохраняем в categoriesFromUrl.

`split(",")`  на categoriesFromUrl  вернёт тебе `["books", "clothes"]`. Всё, с этим массивом можно работать.

2022-02-15 05:53 UTC, vislogurov requested changes

2022-02-15 05:53 UTC, vislogurov commented on src/App.js
> +        if (selectedCategories.includes(selectedItem) && selectedCategories.length === 1) {
Там же самая логика описана в getFilteredProducts. Не?

2022-02-15 05:53 UTC, vislogurov commented on src/components/ProductPage/Category/Category.js
> +class Category extends React.Component {
Тут нет никакого смысла в классовом компоненте, лучше переписать на функцию.

2022-02-15 05:53 UTC, vislogurov commented on src/components/ProductPage/InputCategory/InputCategory.js
> +class InputCategory extends React.Component {
Переписать на функцию

2022-02-15 05:53 UTC, vislogurov commented on src/components/ProductPage/ResetFilters/ResetFilters.js
> +        this.handleClick = this.handleClick.bind(this);
Если метод обяъвлять как стрелочную функцию, то байндить ничего не нужно.

2022-02-15 05:53 UTC, vislogurov commented on src/utils/getFilteredProducts.js
> +        } else if (selectedCategories.includes(item.category)) {
А если  не `includes`, то что произойдёт? Сейчас функция не обрабатывает такой кейс.

2022-02-15 05:53 UTC, vislogurov commented on src/components/ProductPage/ResetFilters/ResetFilters.js
> +                <button
Указывай явно аттрибут type у button, если этого не сделать в явном виде, то браузер сам будет решать — могут быть сюрпризы.

2022-02-15 05:53 UTC, vislogurov commented on src/components/ProductPage/ProductPage.js
>                          <ProductsList
filteredProducts напрямую не юзаются в ProductPage. Есть смысл тогда получать их в целевом компоненте из контекста

2022-03-28 05:47 UTC, vislogurov approved these changes

2022-03-28 14:29 UTC, merged