add components for h1 and ul
PavelProl/junior-course-boilerplate pull request #2
Opened 2021-06-13 19:31 UTC by PavelProl

2021-06-14 07:38 UTC, vislogurov requested changes

2021-06-14 07:38 UTC, vislogurov commented on src/components/ProductsList/ProductsList.js
> +    const products = data.map(function(product) {
продукты должны приходить из пропсов, а не браться напрямую из json. Что будет, если тебе нужно будет другой json отрендерить? Придётся копипатстить компонент ещё раз.

А передача даннных через пропсы делает компонент универсальным и переиспользуемым.

2021-06-15 05:32 UTC, vislogurov requested changes

2021-06-15 05:32 UTC, vislogurov commented on src/components/ProductPageTitle/ProductPageTitle.js
> +import s from './ProductPageTitle.module.css';
Импортишь s но потом нигде не используешь. Добавь стиль по классу для h1 — стили по тэгу это плохая практика, попав в общий бандл стиль по тэгу "растечётся" по всему приложению, нам это не всегда нужно.

2021-06-15 05:32 UTC, vislogurov commented on src/components/ProductsList/ProductsList.js
> +import imgProduct1 from './img/img1.jpg';
Предлагаю пути для изображений положить в products.json.

2021-06-15 05:32 UTC, vislogurov commented on src/components/ProductsList/ProductsList.module.css
> +ul {
селектор по тэгу

2021-06-15 05:32 UTC, vislogurov commented on src/index.js
> +            <div>
Кажется тут отличное место для `main`

2021-06-15 05:32 UTC, vislogurov commented on src/index.js
> +<ProductPage />,
ProductPage это лишь одна из страниц, будут другие. Нужно сделать общий компонент App и в него заимпортить ProductPage. И уже App передать в ReactDOM.render()

2021-06-15 05:32 UTC, vislogurov commented on src/components/ProductItem/ProductItem.js
> +    <div className={cx(s.goods, { [s.goodsNone]: !isInStock })}>
Если это часть ul, то почему это div?

2021-06-15 05:32 UTC, vislogurov commented on src/components/ProductItem/ProductItem.js
> +import s from 'csssr-school-product-card/src/index.module.css';
Тебе не кажется странным, что мы установили целый компонент, но заимпортили из него только стили?
В установке компонента потерялся весь смысл — ты скопипастил разметку для него. Зачем? Она же уже готова была.

Что у нас в задании? `Замени li на специально заготовленный сторонний компонент. Изучи его API и пробрось туда необходимые props.`

`import ProductItem from 'csssr-school-product-card';` Вот всё, что нужно было сделать, осталось только прокинуть пропсы)

2021-06-15 05:32 UTC, vislogurov commented on src/components/ProductsList/ProductsList.js
> +                <ProductItem
Почему это делается "руками", а не через map/for/любой другой итератор? Что будет, если нужно несколько десятков компонентов отрендерить?

2021-06-15 10:05 UTC, PavelProl commented on src/index.js
> +            <div>
Не совсем понял про main. Что это?

2021-06-15 11:09 UTC, vislogurov commented on src/index.js
> +            <div>
https://developer.mozilla.org/ru/docs/Web/HTML/Element/main
Это семантический тэг

2021-06-15 11:11 UTC, PavelProl commented on src/index.js
> +            <div>
Не сразу сообразил, спасибо

2021-06-15 11:29 UTC, PavelProl commented on src/components/ProductItem/ProductItem.js
> +    <div className={cx(s.goods, { [s.goodsNone]: !isInStock })}>
Я импортировал,  как нужно, компонент. Он возвращается в виде дива. Нужно отрендерить ul, в нем отрендерить li, а туда отрендерить компонент ProductItem?

2021-06-15 11:32 UTC, vislogurov commented on src/components/ProductItem/ProductItem.js
> +    <div className={cx(s.goods, { [s.goodsNone]: !isInStock })}>
Я вижу отдельный импорт стилей из компонента, но не импорт комопонента целиком. Да, нужно в li прокинуть ProductItem.

2021-06-15 11:36 UTC, PavelProl commented on src/components/ProductItem/ProductItem.js
> +    <div className={cx(s.goods, { [s.goodsNone]: !isInStock })}>
Ага. Пока не добавил код. Доделываю, залью чуть позже

2021-06-15 11:56 UTC, PavelProl commented on src/index.js
> +            <div>
Получается, что мы рендерим App внутри дива с id "root", а в нем будет main с содержимым (заголовок, список). Так?

2021-06-15 12:00 UTC, vislogurov commented on src/index.js
> +            <div>
да

2021-06-17 06:27 UTC, PavelProl commented on src/components/ProductsList/ProductsList.js
> +                <ProductItem
Вопрос понял, но как я могу сделать через map или другой итератор, если каждый item имеет свою цену, свое название, свою картинку и т.д.? нужно занести items в какой-то массив/объект/json?

2021-06-17 06:32 UTC, vislogurov commented on src/components/ProductsList/ProductsList.js
> +                <ProductItem
да, тебе нужно внести эту инфу в products.json и брать оттуда

2021-06-17 06:42 UTC, vislogurov requested changes

2021-06-17 06:42 UTC, vislogurov commented on src/components/ProductPage/ProductsList/ProductsList.js
> +const ratingComponent = ({ isFilled }) => {
Если это компонент, то почему он не в отдельной директории? Такие "звёзды" могут где-то ещё понадобиться — не тащить же туда для этого ProductList

2021-06-18 07:39 UTC, vislogurov commented on src/components/ProductsList/ProductsList.js
> +    const products = data.map(function(product) {
Этот момент не поправлен

2021-06-18 07:39 UTC, vislogurov commented on src/components/ProductsList/ProductsList.js
> +    const products = data.map(function(product) {
https://github.com/PavelProl/junior-course-boilerplate/pull/2#commitcomment-52337813

2021-06-20 17:04 UTC, vislogurov requested changes

2021-06-20 17:04 UTC, vislogurov commented on src/components/ProductPage/ProductsList/ProductsList.js
> +import ss from '../ProductItem/ProductItem.module.css';
Каждый раз когда в один ui-компонент ты напрямую тянешь что-то из другого компонента, нужно спрашивать себя "А точно ли я делаю всё правильно? Я же только что нарушил модульность и изолированность компонента и добавил лишнюю связь"

Почему ты импортишь стили из ProductItem в другой компонент? Эти стили часть ProductItem и только его.
Более того, ты добавил в PruductItem правило
```
.productItem {
  margin-bottom: 55px;
}
```
А если в другом компоненте нужен будет отступ в 50px? Тогда придётся новое правило в блок добалять. У блока не может быть внешних отступов, потому что мы не можем до конца знать, где ещё его захотят переиспользовать. Поэтому отступы должен добавить конечный "родитель". В твоём случае стиль `productItem` должен принадлежать ProductsList'y.

P.S слышал про БЭМ?
P.S.S где propTypes твоего компонента?

2021-06-20 17:04 UTC, vislogurov commented on src/components/ProductPage/ProductsList/ProductsList.js
> +            <ProductItem isInStock={product.isInStock} img={product.img} title={product.title} price={product.price} subPriceContent={product.subPriceContent} maxRating={product.maxRating} rating={pr
Это неудобно читать. Хорошей практикой принято записывать пропсы столбиком, если их много
```
<ProductItem
     isInStock={product.isInStock}
     img={product.img} 
     title={product.title} 
     price={product.price}
     ...
/>
```

2021-06-20 17:09 UTC, vislogurov requested changes

2021-06-20 17:09 UTC, vislogurov commented on src/components/ProductPage/ratingComponent/ratingComponent.js
> +    return <div className={isFilled && 'starFill'} />;
А если выражение вернёт false?) Острожнее с булевыми операторами.

2021-06-20 19:35 UTC, PavelProl commented on src/components/ProductPage/ratingComponent/ratingComponent.js
> +    return <div className={isFilled && 'starFill'} />;
Понял. Но тут пока мы ничего не делаем с "рейтингом" ?

2021-06-20 19:38 UTC, PavelProl commented on src/components/ProductPage/ProductsList/ProductsList.js
> +import ss from '../ProductItem/ProductItem.module.css';
Думаю, это все 30-градусная жара. Исправил конечно. Про БЭМ читал. 
про проп тайпс момент правильно исправил?

2021-08-18 13:16 UTC, vislogurov requested changes

2021-08-18 13:16 UTC, vislogurov commented on src/App.js
> +            filteredProducts: getFilteredProducts(data, minValue, maxValue)
Почему тут data передвётся как аргумент? Как она тогдв в конечном компоненте попадёт в вызов formSubmit? Тебе нужно вот эту data фильтровать `import data from './products.json';`

2021-08-18 13:16 UTC, vislogurov commented on src/components/ProductPage/ProductsFilter/ProductsFilter.js
> +        e.preventDefault();
`e.preventDefault();` должен идти первым, иначе по сабмиту у тебя браузер перезагрузит страницу и список не успеет отфильтроваться.

В твоем случае **сначала** вызывается submit, и только потом ты его пытаешься отменить через `preventDefault`. Такая запись не имеет никакого смысла, тк эта строчка просто не будет выполнена никогда)

2021-08-18 13:16 UTC, vislogurov commented on src/components/ProductPage/ProductsFilter/ProductsFilter.js
> +        this.props.formSubmit(arr, minValue, maxValue);
Откуда тут взяться arr? Откуда она придёт?

2021-08-26 06:50 UTC, vislogurov approved these changes

2021-08-26 14:55 UTC, merged